"""Design-system source of truth (Phase 0 of REDESIGN_PLAN).

`docs/_design_system/tokens.css` and `base.css` are BUILD OUTPUTS emitted from here,
exactly the way `docs/style.css` is emitted by `17_build_site.py`. They are never
hand-edited: anything under `docs/` that no generator emits is deleted by
`daily_refresh.ps1`'s `git clean -fd docs data` on the next weekday run.

Phase 0 is defined by its acceptance criterion -- NOTHING VISUALLY CHANGES. Two
mechanisms guarantee that, and both must survive future edits:

  1. `tokens.css` declares custom properties only. Declaring an unused `--fs-h1` cannot
     move a pixel. The colour/type/`--wrap` values are copied verbatim from the existing
     `style.css` `:root`, so even the *used* ones resolve identically.
  2. Every rule in `base.css` is scoped under `.ds-v2`, and no page carries that class
     yet (REDESIGN_PLAN 5.4). Phase 1 adds `<body class="ds-v2">` to the pilot page only;
     removing it reverts that one page and nothing else.

Both files are `<link>`ed BEFORE `style.css`. That ordering is load-bearing: `.grid`,
`.metrics`, `.block` and friends exist in both sheets at equal specificity, so the sheet
that loads LAST wins. `style.css` must keep winning until a page opts in.

Breakpoints live here as PYTHON constants, not only as CSS variables, because custom
properties cannot be used in `@media` queries -- `@media (max-width: var(--bp-sm))` works
in no browser. The Python constants are what actually keep the ten generators agreeing.
"""

# --- breakpoints: 360/560/820/880/1100 consolidated to 640/900/1200 -------------
# 1100 is NOT in this list: it survives as `--wrap`, a container width, not a breakpoint.
BP_SM, BP_MD, BP_LG = 640, 900, 1200

# --- chart geometry, mirrored into tokens.css so CSS and Plotly cannot drift ----
CHART = {
    "h_sm": 320, "h_lg": 420,          # standard charts
    "h_tall_sm": 420, "h_tall_lg": 640,  # heatmaps only
    "min_h": 280, "max_h": 460,        # the A4 gate bounds @375
}

FONTS = ("Inter", "Spectral", "JetBrains Mono")   # A9: nothing else may appear

TOKENS = """/* GENERATED by scripts/design_system.py -- do not edit under docs/. */
:root{
  /* ---- colour: copied verbatim from style.css, resolves identically ---- */
  --bg:#fafafa; --panel:#ffffff;
  --ink:#111111; --sec:#555555; --muted:#888888;
  --line:#e5e5e5; --line-strong:#d4d4d4;
  --accent:#0a2540;                     /* Oxford blue, NOT #252D5D (open item 2) */
  --accent-tint:rgba(10,37,64,.045); --accent-line:rgba(10,37,64,.20);
  --pos:#0a5d3a; --neg:#7c2d12;
  --st-green:#0a5d3a; --st-blue:#1e3a8a; --st-purple:#5b21b6; --st-gray:#6b7280;

  /* ---- type stacks: copied verbatim ---- */
  --serif:'Spectral',Charter,"Iowan Old Style",Cambria,Georgia,serif;
  --sans:'Inter',system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
  --mono:'JetBrains Mono',ui-monospace,"SF Mono",Menlo,Consolas,monospace;

  --wrap:min(1100px,92vw);

  /* ---- NEW: fluid type scale, no per-breakpoint overrides ---- */
  --fs-h1:clamp(26px,4.2vw,40px);
  --fs-h2:clamp(19px,2.2vw,25px);
  --fs-h3:clamp(16px,1.6vw,19px);
  --fs-body:clamp(15px,1.05vw,16.5px);
  --fs-sm:clamp(13px,1vw,14px);
  --fs-xs:12px;                         /* HARD FLOOR for prose */
  --fs-label:11px;                      /* uppercase .06em labels only */

  /* ---- NEW: spacing, 4px base ---- */
  --sp-1:4px; --sp-2:8px; --sp-3:12px; --sp-4:16px;
  --sp-6:24px; --sp-8:32px; --sp-12:48px; --sp-16:64px;

  /* ---- NEW: breakpoints. Documentation + JS only; @media cannot read these. ---- */
  --bp-sm:%(sm)dpx; --bp-md:%(md)dpx; --bp-lg:%(lg)dpx;

  /* ---- NEW: chart heights, mirrored from design_system.CHART ---- */
  --chart-h-sm:%(csm)dpx; --chart-h-lg:%(clg)dpx;
  --chart-h-tall-sm:%(tsm)dpx; --chart-h-tall-lg:%(tlg)dpx;

  --gutter-sm:14px; --gutter-lg:24px;
}
""" % {"sm": BP_SM, "md": BP_MD, "lg": BP_LG,
       "csm": CHART["h_sm"], "clg": CHART["h_lg"],
       "tsm": CHART["h_tall_sm"], "tlg": CHART["h_tall_lg"]}


BASE = """/* GENERATED by scripts/design_system.py -- do not edit under docs/.
   EVERY rule is scoped under .ds-v2. No page carries that class until Phase 1 opts
   one in (REDESIGN_PLAN 5.4), so this sheet is inert by construction. Adding an
   unscoped rule here silently ends that guarantee -- don't. */

/* min-width:0 is BUILT IN, not remembered per-site: this is the 2026-08-11 .tile
   blowout encoded as a component invariant. A grid/flex item defaults to
   min-width:auto, so one wide table or one long mono string blows out the track. */
.ds-v2 .card, .ds-v2 .tile, .ds-v2 .btcard, .ds-v2 .scard{ min-width:0; overflow:hidden; }

.ds-v2 .grid{ display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr);
              gap:var(--sp-6); }
.ds-v2 .grid--1{ grid-template-columns:minmax(0,1fr); }
.ds-v2 .metrics{ display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
                 gap:var(--sp-6); }

/* chart height comes from a token, never from Plotly's 450px default */
.ds-v2 .chart-container{ min-width:0; width:100%%; height:var(--chart-h-lg); }
.ds-v2 .chart-container--tall{ height:var(--chart-h-tall-lg); }

/* the scroll box is a COMPONENT with a fade affordance, not bare overflow */
.ds-v2 .data-table-wrap{ overflow-x:auto; -webkit-overflow-scrolling:touch;
  scrollbar-width:thin;
  -webkit-mask-image:linear-gradient(to right,#000 calc(100%% - 18px),transparent);
          mask-image:linear-gradient(to right,#000 calc(100%% - 18px),transparent); }
.ds-v2 .data-table-wrap>table{ margin:0; }

/* prose floor: nothing below --fs-xs, which is the A5 gate's reason to exist */
.ds-v2 .lede{ font-size:var(--fs-body); }
.ds-v2 .caption,.ds-v2 .note{ font-size:var(--fs-sm); }

@media (max-width:%(sm)dpx){
  .ds-v2 .grid{ grid-template-columns:minmax(0,1fr); gap:var(--sp-4); }
  .ds-v2 .chart-container{ height:var(--chart-h-sm); }
  .ds-v2 .chart-container--tall{ height:var(--chart-h-tall-sm); }
}
@media (min-width:%(sm)dpx) and (max-width:%(md)dpx){
  .ds-v2 .metrics{ grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); }
}
""" % {"sm": BP_SM, "md": BP_MD}


# --- mobile chart tuning (relocated from glossary._MOBILE_CHARTS_JS, 2026-08-31) ---
# Moved verbatim so NAV stops being where structural JS lives. `glossary.NAV` imports
# this, so every generated page keeps the same tuner. The ONLY edit is that the
# breakpoint is read from --bp-sm instead of hardcoded -- and the token resolves to
# 640, the previous literal, so behaviour is unchanged today and cannot drift later.
#
# Plotly neither wraps nor shrinks a title and has no 'font size at this breakpoint'
# option. At a 283px mobile plot width a 45-char title renders ~350-410px wide and is
# silently CLIPPED by `.tile{overflow:hidden}` -- which is why the site passed the
# 375px no-overflow gate while every chart read as truncated: the gate measures the
# DOCUMENT, the clipping happens inside a tile. So the breakpoint is applied from JS.
#
# Desktop is untouched by construction: above the breakpoint the tuner returns early
# before it ever calls relayout. Originals are stashed on first sight and restored on
# the way back up, so a desktop<->mobile resize round-trip is lossless.
MOBILE_CHARTS_JS = """<script>(function(){
var MOB=640,st=new WeakMap();
/* read the breakpoint from --bp-sm so CSS and JS cannot drift; 640 is the fallback
   and the token resolves to that same 640, so both paths agree today. */
try{var _bp=parseInt(getComputedStyle(document.documentElement)
  .getPropertyValue('--bp-sm'),10);if(_bp>0)MOB=_bp;}catch(_e){}
function wrap(t,cpl){
  if(!t)return t;
  var w=String(t).split(' '),ln=[],c='';
  for(var i=0;i<w.length;i++){var n=c?c+' '+w[i]:w[i];
    if(n.length>cpl&&c){ln.push(c);c=w[i];}else{c=n;}}
  if(c)ln.push(c);
  return ln.join('<br>');
}
function tune(){
  if(!window.Plotly)return;
  var mob=window.innerWidth<=MOB;
  document.querySelectorAll('.plotly-graph-div').forEach(function(d){
    if(!d._fullLayout)return;                       /* not rendered yet; a later retry gets it */
    var rect=d.getBoundingClientRect();
    if(!rect.width)return;
    /* re-tune when the width BUCKET changes, not on every pixel: 375->414 must
       re-wrap the title, but a scroll-driven 1px reflow must not relayout. */
    var key=mob?('m'+Math.round(rect.width/30)):'d';
    if(d.__tk===key)return;
    var first=!d.__tk; d.__tk=key;
    var o=st.get(d);
    if(!o){var L=d.layout||{},FL=d._fullLayout;
      o={t:(L.title&&L.title.text)||'',
         ts:(FL.title&&FL.title.font&&FL.title.font.size)||15,
         m:{l:FL.margin.l,r:FL.margin.r,t:FL.margin.t,b:FL.margin.b},
         lg:(L.legend?JSON.parse(JSON.stringify(L.legend)):{}),
         h:FL.height,
         an:(FL.annotations||[]).map(function(a){return a.visible!==false;}),
         md:(d.data||[]).map(function(t){return t.mode;})};
      st.set(d,o);}
    /* Per-point text labels are unreadable once the plot is 283px wide: the
       risk/return map packs 24 asset labels into that space and 22 of the 24
       pairs overlap. Traces that carry many labels drop to markers-only on
       mobile -- the class legend still identifies them and a tap still shows
       the name on hover. The cutoff is 3, not 6: the 4-label Real Asset trace
       still self-overlapped twice at 283px. */
    function modes(mob){
      var chg=false,arr=(d.data||[]).map(function(t,i){
        var m=o.md[i];
        if(!mob||!m||m.indexOf('text')<0)return m;
        if(!t.text||t.text.length<=3)return m;
        chg=true;return m.replace('+text','').replace('text+','').replace('text','markers');});
      if(mob&&!chg)return;
      if(!mob&&!(o.md||[]).some(function(m){return m&&m.indexOf('text')>=0;}))return;
      try{Plotly.restyle(d,{mode:arr});}catch(e){}
    }
    if(!mob){
      if(first)return;                              /* first sight on desktop: nothing to undo */
      var back={'title.text':o.t,'title.font.size':o.ts,
        'margin.l':o.m.l,'margin.r':o.m.r,'margin.t':o.m.t,'margin.b':o.m.b,
        'legend.font.size':(o.lg.font&&o.lg.font.size)||null,
        'legend.orientation':o.lg.orientation||null,
        'legend.x':(o.lg.x===undefined?null:o.lg.x),
        'legend.xanchor':o.lg.xanchor||null,
        'legend.y':(o.lg.y===undefined?null:o.lg.y),
        'legend.yanchor':o.lg.yanchor||null};
      if(d._fullLayout.xaxis){back['xaxis.tickfont.size']=null;back['xaxis.title.font.size']=null;}
      if(d._fullLayout.yaxis){back['yaxis.tickfont.size']=null;back['yaxis.title.font.size']=null;
        if(d._fullLayout.yaxis.type==='log')back['yaxis.dtick']=null;}
      if(o.h)back['height']=o.h;
      o.an.forEach(function(v,i){back['annotations['+i+'].visible']=v;});
      modes(false);
      try{Plotly.relayout(d,back);Plotly.Plots.resize(d);}catch(e){}
      return;}
    /* SCALE the generator's margins, never replace them -- the correlation
       heatmap carries 130px left/bottom margins for its asset labels, and a
       flat 44px left margin would clip them off the chart entirely.
       Margins resolve FIRST because the title is left-anchored at margin.l:
       wrapping against the full div width let every title start 35px in and then
       run 12-23px past the right edge, clipped by .tile{overflow:hidden}. */
    var mL=Math.max(34,Math.round(o.m.l*0.72)),mR=Math.max(10,Math.round(o.m.r*0.5));
    /* ~6.3px per char for Inter at 12.5px; the 8px pad keeps it off the edge. */
    var cpl=Math.max(14,Math.floor((rect.width-mL-8)/6.3));
    var txt=wrap(o.t,cpl),lines=txt?txt.split('<br>').length:0;
    var up={'title.text':txt,'title.font.size':12.5,
      'margin.l':mL,'margin.r':mR,
      'margin.t':(lines>1?26+lines*15:Math.max(34,Math.round(o.m.t*0.8))),
      'margin.b':Math.max(34,Math.round(o.m.b*0.82)),
      'legend.font.size':9.5,'legend.orientation':'h',
      'legend.x':0,'legend.xanchor':'left','legend.y':-0.24,'legend.yanchor':'top'};
    if(d._fullLayout.xaxis){up['xaxis.tickfont.size']=10;up['xaxis.title.font.size']=10.5;}
    if(d._fullLayout.yaxis){up['yaxis.tickfont.size']=10;up['yaxis.title.font.size']=10.5;}
    /* config responsive:true only fires on window-resize EVENTS. A page loaded
       straight into a 375px viewport therefore kept Plotly's default 700px SVG,
       visually clipped to the 283px tile, ticks landing 360px past its right
       edge. (Keep this comment free of `name=number` -- confscan greps it.) */
    /* hline annotations ("stress threshold +0.5", "fed funds 3.63%") are drawn
       INSIDE the plot area and sit on top of the data. At 283px they cover the
       series they annotate. The dotted line itself stays -- only its caption is
       hidden, and the surrounding prose already names the thresholds. This is
       the one defect class the clip check cannot see: it never leaves the div. */
    o.an.forEach(function(_,i){up['annotations['+i+'].visible']=false;});
    /* A log y-axis renders minor decade labels (8, 9) that collide once the
       plot is ~340px tall. Decades only on mobile. */
    if(d._fullLayout.yaxis&&d._fullLayout.yaxis.type==='log')up['yaxis.dtick']=1;
    /* Cap height so a chart is not a full portrait screen -- EXCEPT horizontal
       bar charts with many categories, where the height IS the category axis and
       shrinking it makes the labels collide instead. */
    var hbar=(d.data||[]).some(function(t){return t.type==='bar'&&t.orientation==='h';});
    var ncat=hbar?Math.max.apply(null,(d.data||[]).map(function(t){return (t.y||[]).length;})):0;
    if(o.h&&o.h>360&&!(hbar&&ncat>8))up['height']=340;
    modes(true);
    try{Plotly.relayout(d,up);Plotly.Plots.resize(d);}catch(e){}
  });
}
/* Plotly renders from inline scripts and settles asynchronously (the 40x
   under-report the old iframe gate hit), so poll a few times rather than
   trusting one DOMContentLoaded pass. */
function retry(){[0,250,900,2000,3500].forEach(function(ms){setTimeout(tune,ms);});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',retry);else retry();
var tid;function later(){clearTimeout(tid);tid=setTimeout(tune,160);}
window.addEventListener('resize',later);window.addEventListener('orientationchange',later);
})();</script>"""



# --- <link> tags: ONE definition, referenced at every generator's <head> ----------
# Order is load-bearing (see module docstring): tokens, base, THEN style.css.
CSS_LINKS = ('<link rel="stylesheet" href="_design_system/tokens.css">'
             '<link rel="stylesheet" href="_design_system/base.css">')


def emit(docs_dir):
    """Write tokens.css + base.css under `docs_dir/_design_system/`.

    Called from 17_build_site.py beside the existing style.css write, so the files are
    regenerated on every build and `git clean -fd docs` can never orphan them.
    """
    import os
    out = os.path.join(docs_dir, "_design_system")
    os.makedirs(out, exist_ok=True)
    for name, body in (("tokens.css", TOKENS), ("base.css", BASE)):
        with open(os.path.join(out, name), "w", encoding="utf-8") as fh:
            fh.write(body)
    return out
